using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static DXApplication1.Connection;

namespace DXApplication1.MW3
{
   public class FunctionsMethods
    {
        public static void ModdedClass()
        {
            PS3.SetMemory(29471468U, new byte[1]
{
        byte.MaxValue
});
            PS3.SetMemory(29471459U, new byte[1] { (byte)15 });
            PS3.SetMemory(29464576U, new byte[1984]
            {
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 90,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 132,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 101,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 2,
        (byte) 3,
        (byte) 94,
        (byte) 54,
        (byte) 77,
        (byte) 87,
        (byte) 50,
        (byte) 32,
        (byte) 65,
        (byte) 85,
        (byte) 71,
        (byte) 3,
        (byte) 2,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 40,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 132,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 106,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 110,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 49,
        (byte) 94,
        (byte) 2,
        (byte) 161,
        (byte) 238,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 12,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 106,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 52,
        (byte) 77,
        (byte) 75,
        (byte) 49,
        (byte) 52,
        (byte) 13,
        (byte) 32,
        (byte) 94,
        (byte) 49,
        (byte) 77,
        (byte) 75,
        (byte) 49,
        (byte) 52,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 40,
        (byte) 0,
        (byte) 16,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 106,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 18,
        (byte) 18,
        (byte) 94,
        (byte) 49,
        (byte) 78,
        (byte) 79,
        (byte) 32,
        (byte) 94,
        (byte) 48,
        (byte) 71,
        (byte) 85,
        (byte) 78,
        (byte) 17,
        (byte) 17,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 18,
        (byte) 0,
        (byte) 20,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 102,
        (byte) 0,
        (byte) 49,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 50,
        (byte) 80,
        (byte) 94,
        (byte) 53,
        (byte) 77,
        (byte) 94,
        (byte) 54,
        (byte) 57,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 37,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 15,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 101,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 50,
        (byte) 70,
        (byte) 65,
        (byte) 80,
        (byte) 32,
        (byte) 94,
        (byte) 54,
        (byte) 70,
        (byte) 65,
        (byte) 80,
        (byte) 32,
        (byte) 94,
        (byte) 51,
        (byte) 70,
        (byte) 65,
        (byte) 68,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 8,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 101,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 76,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 49,
        (byte) 84,
        (byte) 89,
        (byte) 80,
        (byte) 69,
        (byte) 32,
        (byte) 94,
        (byte) 57,
        (byte) 57,
        (byte) 53,
        (byte) 17,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 37,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 19,
        (byte) 0,
        (byte) 20,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 101,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 51,
        (byte) 80,
        (byte) 57,
        (byte) 48,
        (byte) 32,
        (byte) 94,
        (byte) 50,
        (byte) 68,
        (byte) 65,
        (byte) 87,
        (byte) 71,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 20,
        (byte) 0,
        (byte) 20,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 107,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 74,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 53,
        (byte) 80,
        (byte) 80,
        (byte) 77,
        (byte) 94,
        (byte) 49,
        (byte) 57,
        (byte) 48,
        (byte) 49,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 5,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 16,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 46,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 101,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 112,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 54,
        (byte) 67,
        (byte) 94,
        (byte) 51,
        (byte) 77,
        (byte) 94,
        (byte) 50,
        (byte) 57,
        (byte) 94,
        (byte) 53,
        (byte) 48,
        (byte) 94,
        (byte) 49,
        (byte) 49,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 11,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 101,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 110,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 14,
        (byte) 94,
        (byte) 50,
        (byte) 77,
        (byte) 94,
        (byte) 54,
        (byte) 161,
        (byte) 94,
        (byte) 50,
        (byte) 54,
        (byte) 15,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 10,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 17,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 13,
        (byte) 0,
        (byte) 132,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 101,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 17,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 76,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 14,
        (byte) 15,
        (byte) 14,
        (byte) 15,
        (byte) 13,
        (byte) 32,
        (byte) 32,
        (byte) 32,
        (byte) 32,
        (byte) 94,
        (byte) 53,
        (byte) 50,
        (byte) 32,
        (byte) 94,
        (byte) 54,
        (byte) 65,
        (byte) 75,
        (byte) 39,
        (byte) 83,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 22,
        (byte) 0,
        (byte) 20,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 13,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 108,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 110,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 5,
        (byte) 94,
        (byte) 53,
        (byte) 67,
        (byte) 79,
        (byte) 68,
        (byte) 78,
        (byte) 186,
        (byte) 186,
        (byte) 98,
        (byte) 70,
        (byte) 114,
        (byte) 105,
        (byte) 101,
        (byte) 110,
        (byte) 100,
        (byte) 108,
        (byte) 121,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 63,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 13,
        (byte) 0,
        (byte) 138,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 63,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 102,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 17,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 114,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 59,
        (byte) 82,
        (byte) 33,
        (byte) 48,
        (byte) 84,
        (byte) 32,
        (byte) 20,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 125,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 22,
        (byte) 0,
        (byte) 31,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 7,
        (byte) 0,
        (byte) 21,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 13,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 108,
        (byte) 0,
        (byte) 92,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 110,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 14,
        (byte) 15,
        (byte) 14,
        (byte) 15,
        (byte) 14,
        (byte) 15,
        (byte) 13,
        (byte) 65,
        (byte) 94,
        (byte) 51,
        (byte) 67,
        (byte) 94,
        (byte) 50,
        (byte) 82,
        (byte) 33,
        (byte) 33,
        (byte) 33,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 36,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 40,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 132,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 106,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 131,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 53,
        (byte) 94,
        (byte) 2,
        (byte) 161,
        (byte) 238,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 23,
        (byte) 0,
        (byte) 25,
        (byte) 0,
        (byte) 35,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 90,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 132,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 106,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 38,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 131,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 51,
        (byte) 67,
        (byte) 79,
        (byte) 68,
        (byte) 78,
        (byte) 186,
        (byte) 186,
        (byte) 98,
        (byte) 70,
        (byte) 114,
        (byte) 105,
        (byte) 101,
        (byte) 110,
        (byte) 100,
        (byte) 108,
        (byte) 121,
        (byte) 174,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 35,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 63,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 138,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 63,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 140,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 102,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 17,
        (byte) 0,
        (byte) 10,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 0,
        (byte) 114,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 1,
        (byte) 2,
        (byte) 3,
        (byte) 17,
        (byte) 19,
        (byte) 6,
        (byte) 94,
        (byte) 48,
        (byte) 72,
        (byte) 170,
        (byte) 169,
        (byte) 107,
        (byte) 161,
        (byte) 110,
        (byte) 103,
        (byte) 13,
        (byte) 15,
        (byte) 14,
        (byte) 15,
        (byte) 64,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 23,
        (byte) 0,
        (byte) 25,
        (byte) 0,
        (byte) 35,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 39,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 22,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 20,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 57,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 102,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 131,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 94,
        (byte) 54,
        (byte) 171,
        (byte) 72,
        (byte) 166,
        (byte) 116,
        (byte) 109,
        (byte) 97,
        (byte) 114,
        (byte) 107,
        (byte) 101,
        (byte) 114,
        (byte) 122,
        (byte) 33,
        (byte) 33,
        (byte) 171,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 23,
        (byte) 0,
        (byte) 25,
        (byte) 0,
        (byte) 40,
        (byte) 0,
        (byte) 35,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 3,
        (byte) 40,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 9,
        (byte) 0,
        (byte) 132,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 18,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 106,
        (byte) 0,
        (byte) 15,
        (byte) 0,
        (byte) 48,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 97,
        (byte) 0,
        (byte) 131,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 22,
        (byte) 22,
        (byte) 94,
        (byte) 49,
        (byte) 81,
        (byte) 167,
        (byte) 32,
        (byte) 94,
        (byte) 54,
        (byte) 65,
        (byte) 108,
        (byte) 108,
        (byte) 32,
        (byte) 94,
        (byte) 59,
        (byte) 68,
        (byte) 97,
        (byte) 121,
        (byte) 23,
        (byte) 23,
        (byte) 0,
        (byte) 118,
        (byte) 0,
        (byte) 1,
        (byte) 0,
        (byte) 3,
        (byte) 0,
        (byte) 8,
        (byte) 0,
        (byte) 19,
        (byte) 0,
        (byte) 23,
        (byte) 0,
        (byte) 25,
        (byte) 0,
        (byte) 40,
        (byte) 0,
        (byte) 33,
        (byte) 0,
        (byte) 35,
        (byte) 0,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 4,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 6,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 21,
        (byte) 2,
        (byte) 19,
        (byte) 2,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0,
        (byte) 0
            });
        }

        public static void UnlockEliteCamo()
        {
            byte[] array = new byte[]
            {
                byte.MaxValue
            };
            PS3.SetMemory(29471468u, array);
        }
        public static void Prestige20Lvl80()
        {
            byte[] array3 = new byte[]
            {
                20
            };
            PS3.SetMemory(29463676u, array3);
            byte[] array4 = new byte[]
            {
                24,
                165,
                26,
                0,
                0
            };
            PS3.SetMemory(29463148u, array4);
        }


        public static void AllWeaponlvl31()
        {
            byte[] array2 = new byte[]
              {
                    byte.MaxValue,
                    byte.MaxValue,
                    0,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    161,
                    0,
                    224,
                    165,
                    161,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    161,
                    0,
                    174,
                    10,
                    161,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    161,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    0,
                    224,
                    165,
                    26,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    17,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30,
                    30
              };
            PS3.SetMemory(29463156u, array2);
        }
    }
}
